#!/usr/bin/env node
'use strict';

/**
 * genArchSnapshot.js
 * 
 * Generates an auto-updated snapshot of the Atlas06 architecture:
 *   - File tree with sizes
 *   - Route inventory (extracted from source)
 *   - Model field counts
 *   - Config key summary
 *   - Dependency list
 * 
 * Output: docs/SNAPSHOT.md (auto-generated, don't edit manually)
 * 
 * Usage:
 *   node scripts/genArchSnapshot.js
 *   npm run docs:snapshot
 */

const fs   = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const OUT  = path.join(ROOT, 'docs', 'SNAPSHOT.md');

// ── Helpers ──────────────────────────────────────────────────────────────────

function readFile(relPath) {
  const abs = path.join(ROOT, relPath);
  try { return fs.readFileSync(abs, 'utf8'); } catch { return null; }
}

function sizeLabel(bytes) {
  if (bytes < 1024) return `${bytes}B`;
  return `${(bytes / 1024).toFixed(1)}KB`;
}

function walk(dir, prefix = '', depth = 0) {
  if (depth > 3) return [];
  const entries = [];
  const skip = ['node_modules', '.git', 'media', 'logs', '{src', '.DS_Store'];

  try {
    const items = fs.readdirSync(dir, { withFileTypes: true })
      .filter(d => !skip.includes(d.name))
      .sort((a, b) => {
        // Directories first
        if (a.isDirectory() && !b.isDirectory()) return -1;
        if (!a.isDirectory() && b.isDirectory()) return 1;
        return a.name.localeCompare(b.name);
      });

    for (const item of items) {
      const full = path.join(dir, item.name);
      if (item.isDirectory()) {
        entries.push(`${prefix}📁 ${item.name}/`);
        entries.push(...walk(full, prefix + '  ', depth + 1));
      } else {
        const stat = fs.statSync(full);
        entries.push(`${prefix}📄 ${item.name} (${sizeLabel(stat.size)})`);
      }
    }
  } catch {}

  return entries;
}

// ── Extract routes from source files ─────────────────────────────────────────

function extractRoutes(filePath) {
  const content = readFile(filePath);
  if (!content) return [];

  const routes = [];
  const routeRegex = /router\.(get|post|put|patch|delete)\s*\(\s*['"`]([^'"`]+)['"`]/gi;
  let match;

  while ((match = routeRegex.exec(content)) !== null) {
    routes.push({
      method: match[1].toUpperCase(),
      path: match[2],
    });
  }

  return routes;
}

// ── Extract model fields ─────────────────────────────────────────────────────

function extractModelInfo(filePath) {
  const content = readFile(filePath);
  if (!content) return null;

  const collMatch = content.match(/collection:\s*['"`]([^'"`]+)['"`]/);
  const indexMatches = [...content.matchAll(/\.index\(/g)];
  const fieldMatches = [...content.matchAll(/^\s+(\w+):\s+/gm)];

  return {
    collection: collMatch ? collMatch[1] : '(default)',
    indexCount: indexMatches.length,
    fieldCount: fieldMatches.length,
  };
}

// ── Extract dependencies ─────────────────────────────────────────────────────

function getDeps() {
  const pkg = JSON.parse(readFile('package.json') || '{}');
  const deps = Object.entries(pkg.dependencies || {}).map(([name, ver]) => ({ name, ver }));
  const devDeps = Object.entries(pkg.devDependencies || {}).map(([name, ver]) => ({ name, ver, dev: true }));
  return { deps, devDeps, version: pkg.version, nodeEngine: pkg.engines?.node };
}

// ── Extract schedule config ──────────────────────────────────────────────────

function getScheduleInfo() {
  const raw = readFile('config/schedule.json');
  if (!raw) return null;
  try {
    const config = JSON.parse(raw);
    return {
      totalCities: config.cities?.length || 0,
      frequencies: {
        weekly: config.cities?.filter(c => c.frequency === 'weekly').length || 0,
        biweekly: config.cities?.filter(c => c.frequency === 'biweekly').length || 0,
        monthly: config.cities?.filter(c => c.frequency === 'monthly').length || 0,
      },
      staleness: config.staleness || {},
      enrichment: config.enrichment || {},
    };
  } catch { return null; }
}

// ── Extract env config ───────────────────────────────────────────────────────

function getEnvKeys() {
  const content = readFile('.env.example') || readFile('.env');
  if (!content) return [];
  return content.split('\n')
    .filter(l => l.match(/^[A-Z_]+=/) && !l.startsWith('#'))
    .map(l => l.split('=')[0]);
}

// ── Generate ─────────────────────────────────────────────────────────────────

function generate() {
  const now = new Date().toISOString().replace('T', ' ').split('.')[0];
  const lines = [];

  lines.push(`# 📸 Atlas06 — Architecture Snapshot`);
  lines.push(``);
  lines.push(`> **Auto-generated** by \`node scripts/genArchSnapshot.js\``);
  lines.push(`> Last generated: **${now} UTC**`);
  lines.push(`>`);
  lines.push(`> ⚠️ Do NOT edit this file manually. Run the script to regenerate.`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  // ── Package Info ─────────────────────────────────────────────────────────
  const { deps, devDeps, version, nodeEngine } = getDeps();
  lines.push(`## Package Info`);
  lines.push(``);
  lines.push(`| Key | Value |`);
  lines.push(`|-----|-------|`);
  lines.push(`| Version | \`${version || '—'}\` |`);
  lines.push(`| Node Engine | \`${nodeEngine || '—'}\` |`);
  lines.push(`| Dependencies | ${deps.length} |`);
  lines.push(`| Dev Dependencies | ${devDeps.length} |`);
  lines.push(``);

  // ── File Tree ────────────────────────────────────────────────────────────
  lines.push(`## File Tree`);
  lines.push(``);
  lines.push('```');
  lines.push(...walk(ROOT));
  lines.push('```');
  lines.push(``);

  // ── Route Inventory ────────────────────────────────────────────────────
  lines.push(`## Route Inventory`);
  lines.push(``);

  const routeFiles = [
    { file: 'src/api/indexRoutes.js', prefix: '' },
    { file: 'src/api/crawlRoutes.js', prefix: '/api/crawl' },
    { file: 'src/api/gymRoutes.js', prefix: '/api/gyms' },
    { file: 'src/api/systemRoutes.js', prefix: '/api/system' },
  ];

  let totalRoutes = 0;
  for (const { file, prefix } of routeFiles) {
    const routes = extractRoutes(file);
    totalRoutes += routes.length;
    lines.push(`### ${path.basename(file)} (${routes.length} routes)`);
    lines.push(``);
    if (routes.length) {
      lines.push(`| Method | Full Path |`);
      lines.push(`|--------|-----------|`);
      for (const r of routes) {
        lines.push(`| \`${r.method}\` | \`${prefix}${r.path}\` |`);
      }
    } else {
      lines.push(`_No routes extracted_`);
    }
    lines.push(``);
  }
  lines.push(`**Total routes: ${totalRoutes}**`);
  lines.push(``);

  // ── Model Summary ──────────────────────────────────────────────────────
  lines.push(`## Database Models`);
  lines.push(``);

  const modelFiles = [
    'src/db/gymModel.js',
    'src/db/reviewModel.js',
    'src/db/photoModel.js',
    'src/db/crawlMetaModel.js',
    'src/db/crawlJobModel.js',
    'src/db/categoryModel.js',
    'src/db/amenityModel.js',
    'src/db/placeTypeModel.js',
    'src/db/gymChangeLogModel.js',
  ];

  lines.push(`| Model File | Collection | Fields | Indexes |`);
  lines.push(`|-----------|-----------|--------|---------|`);
  for (const f of modelFiles) {
    const info = extractModelInfo(f);
    if (info) {
      lines.push(`| \`${path.basename(f)}\` | \`${info.collection}\` | ~${info.fieldCount} | ${info.indexCount} |`);
    }
  }
  lines.push(``);

  // ── Schedule ───────────────────────────────────────────────────────────
  const sched = getScheduleInfo();
  if (sched) {
    lines.push(`## Schedule Config`);
    lines.push(``);
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Total cities | ${sched.totalCities} |`);
    lines.push(`| Weekly | ${sched.frequencies.weekly} |`);
    lines.push(`| Biweekly | ${sched.frequencies.biweekly} |`);
    lines.push(`| Monthly | ${sched.frequencies.monthly} |`);
    lines.push(`| Staleness threshold | ${sched.staleness.enrichmentThresholdDays || '—'} days |`);
    lines.push(`| Max stale days | ${sched.staleness.maxStaleDays || '—'} |`);
    lines.push(`| Enrichment threshold | ${sched.enrichment.completenessThreshold || '—'}% |`);
    lines.push(``);
  }

  // ── Dependencies ───────────────────────────────────────────────────────
  lines.push(`## Dependencies`);
  lines.push(``);
  lines.push(`| Package | Version | Purpose |`);
  lines.push(`|---------|---------|---------|`);

  const purposes = {
    'express': 'REST API framework',
    'mongoose': 'MongoDB ODM',
    'bullmq': 'Job queue (Redis-backed)',
    'ioredis': 'Redis client',
    'playwright': 'Browser automation',
    'playwright-extra': 'Playwright plugin system',
    'puppeteer-extra-plugin-stealth': 'Anti-bot detection bypass',
    'sharp': 'Image processing (resize, thumbnail)',
    'axios': 'HTTP client for media downloads',
    'winston': 'Structured logging',
    'winston-daily-rotate-file': 'Daily rotating log files',
    'node-cron': 'Cron scheduler',
    'helmet': 'Security headers',
    'cors': 'CORS middleware',
    'compression': 'Response compression',
    'express-rate-limit': 'API rate limiting',
    'express-validator': 'Request validation',
    'morgan': 'HTTP request logger',
    'slugify': 'URL-safe slug generation',
    'geolib': 'Geospatial distance calculations',
    'generic-pool': 'Resource pooling',
    'p-limit': 'Concurrency limiting',
    'p-retry': 'Retry with backoff',
    'uuid': 'UUID generation',
    'dotenv': 'Environment variable loading',
    'swagger-jsdoc': 'Swagger spec from JSDoc',
    'swagger-ui-express': 'Interactive API documentation',
    'nodemon': 'Dev auto-restart',
  };

  for (const d of [...deps, ...devDeps]) {
    const purpose = purposes[d.name] || (d.dev ? 'Dev tooling' : '—');
    lines.push(`| \`${d.name}\` | \`${d.ver}\` | ${purpose}${d.dev ? ' *(dev)*' : ''} |`);
  }
  lines.push(``);

  // ── Environment Variables ──────────────────────────────────────────────
  const envKeys = getEnvKeys();
  if (envKeys.length) {
    lines.push(`## Environment Variables (${envKeys.length} keys)`);
    lines.push(``);
    lines.push('```');
    for (const k of envKeys) {
      lines.push(k);
    }
    lines.push('```');
    lines.push(``);
  }

  // ── Write output ───────────────────────────────────────────────────────
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, lines.join('\n'));
  console.log(`✅ Snapshot generated: ${OUT}`);
  console.log(`   ${totalRoutes} routes, ${modelFiles.length} models, ${deps.length} dependencies`);
}

generate();
